# Supabase OTA Module Configuration
# This file defines how modules are built and uploaded to Supabase Storage

supabase:
  bucket_name: "ota-modules"
  storage_endpoint: "/storage/v1/object"
  manifest_file: "manifest.json"
  
  # Upload options
  options:
    use_upsert: true          # Use x-upsert header to overwrite existing files
    content_types:
      binary: "application/octet-stream"
      metadata: "application/json"
      manifest: "application/json"

versioning:
  scheme: "semantic"          # semantic, timestamp, or custom
  base_version: "1.2"         # major.minor (patch auto-incremented)
  auto_increment: true
  include_commit: true        # Include git commit hash in metadata

modules:
  speed_governor:
    name: "speed_governor"
    description: "Speed governor module for TATA EV Nexon - fixes highway speed limit issue"
    priority: "high"
    build_dir: "build"
    binary_name: "speed_governor.bin"
    category: "safety"
    dependencies: []
    
  distance_sensor:
    name: "distance_sensor"
    description: "Ultrasonic distance sensor module with cm/mm output support"
    priority: "normal" 
    build_dir: "build"
    binary_name: "distance_sensor.bin"
    category: "sensors"
    dependencies: []

# Upload paths structure
paths:
  latest: "{module}/latest/"
  versioned: "{module}/{version}/"
  manifest: "manifest.json"
  
  # Archive old versions after this many releases
  archive_after: 5

# Metadata template for all modules
metadata_template:
  module_name: "{module}"
  version: "{version}"
  sha256: "{hash}"
  signature: "{signature}"
  build_time: "{timestamp}"
  commit_hash: "{commit}"
  priority: "{priority}"
  description: "{description}"
  size: "{size}"
  category: "{category}"
  dependencies: "{dependencies}"
  
# Build configuration
build:
  toolchain_path: "$HOME/.espressif/xtensa-esp32-elf/bin"
  clean_before_build: true
  parallel_builds: true
  
  # ESP32 specific settings
  esp32:
    optimization: "-Os"
    target: "esp32"
    compile_flags:
      - "-mlongcalls"
      - "-ffunction-sections" 
      - "-fdata-sections"
      - "-fPIC"
      - "-nostdlib"
      - "-std=c99"
      - "-Wall"

# Security settings
security:
  enable_signing: false       # Set to true when ready to implement
  signature_algorithm: "RSA-SHA256"
  placeholder_signature: "placeholder-for-demo-signature"
  
# Notification settings (for future use)
notifications:
  slack:
    enabled: false
    webhook_url: ""
  
  email:
    enabled: false
    recipients: []

# Development settings
development:
  local_testing: true
  mock_uploads: false
  verbose_logging: true 